### ISSUE TITLE
Github creation and organization 

### ISSUE THREAD

**Issue by HadleyKing** [UCI-GREGoR/retool#12]
@HadleyKing will discuss with @ericvilainmdphd about creating a Git Organization to house various repositories
- [x] Also check with UCI folks about what might already be there

**Comment by lightning-auriga** [comment]
This is cool. I've run into an issue with a private repo: GitHub is refusing to enforce branch protection rules on a private repo for a non-enterprise organization. I *think* that this ultimately means that GitHub will start enforcing the rules once the repo is toggled to public, because that's GitHub's MO. But there's a chance that I'll try it in the new year, branch protections will still be disabled, and I'll start banging around asking for a paid organization.
